admbreno/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('clientesF.urls')),
    path("admin/", admin.site.urls),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),   
]

clientesF/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import lista_clientes
from .views import criar_cliente
from .views import editar_cliente
from .views import excluir_cliente
from .views import (
    cadastro_veiculo,
    lista_veiculos,
    edita_veiculo,
    exclui_veiculo,
    criar_servico,
    cadastro_servico,
    lista_servicos,
    exclui_servico,
    edita_servico,
    cadastrar_fornecedor,
    fornecedores_list,
    fornecedor_edit,
    fornecedor_delete,
)

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login.html'), name='logout'),
    path('lista_clientes/', views.lista_clientes, name='lista_clientes'),
    path('criar_cliente/', views.criar_cliente, name='criar_cliente'),
    path('editar_cliente/<int:pk>/', editar_cliente, name='editar_cliente'),
    path('excluir_cliente/<int:pk>/', excluir_cliente, name='excluir_cliente'),
    path('lista_veiculos/', lista_veiculos, name='lista_veiculos'),
    path('cadastro_veiculo/', cadastro_veiculo, name='cadastro_veiculo'),
    path('edita_veiculo/<int:pk>/', edita_veiculo, name='edita_veiculo'),
    path('exclui_veiculo/<int:pk>/', exclui_veiculo, name='exclui_veiculo'),
    path('servico/novo/<int:veiculo_id>/', cadastro_servico, name='cadastro_servico'),
    path('lista_servicos/', lista_servicos, name='lista_servicos'),
    path('exclui_servico/<int:pk>/', exclui_servico, name='exclui_servico'),
    path('edita_servico/<int:pk>/', edita_servico, name='edita_servico'),
    path('../accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('cadastrar_fornecedor/', cadastrar_fornecedor, name='cadastrar_fornecedor'),
    path('fornecedores_list/', fornecedores_list, name='fornecedores_list'),
    path('fornecedor_edit/<int:pk>/', fornecedor_edit, name='fornecedor_edit'),
    path('fornecedor_delete/<int:pk>/', fornecedor_delete, name='fornecedor_delete'),

]

clientesF/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):
    data_cadastro = models.DateField(auto_now = True)
    hora_cadastro = models.TimeField(auto_now = True)
    nome = models.CharField(max_length=100)
    sobrenome = models.CharField(max_length=100)
    cpf = models.CharField(max_length = 14)
    data_nascimento = models.DateField ()
    profissao = models.CharField(max_length=100)
    telefone = models.CharField(max_length = 15)
    celular = models.CharField(max_length = 15)
    cep = models.CharField(max_length=9)
    endereco = models.CharField(max_length=200)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length = 100)
    uf = models.CharField(max_length = 2)
    email = models.EmailField()

    def __str__(self):
        return self.nome
    

class Veiculo(models.Model):
    data_cadastro = models.DateField(auto_now = True)
    hora_cadastro = models.TimeField(auto_now = True)
    cliente = models.ForeignKey(Cliente, on_delete = models.CASCADE, related_name = 'veiculos')
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)
    ano = models.IntegerField()
    placa = models.CharField(max_length=7, unique=True)

    def __str__(self):
        return self.placa
    
class Servico(models.Model):
    data_cadastro = models.DateField(auto_now = True)
    hora_cadastro = models.TimeField(auto_now = True)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    data_entrega = models.DateField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name='servicos')
    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE, related_name='servicos')
    descricao = models.CharField(max_length = 200)
    detalhes = models.TextField(blank=True, null=True)
    
    
class Fornecedor(models.Model):
    RAZAO_SOCIAL_MAX_LENGTH = 200
    NOME_FANTASIA_MAX_LENGTH = 200
    SEGMENTO_MAX_LENGTH = 100
    CONTATO_MAX_LENGTH = 200
    TELEFONE_MAX_LENGTH = 20
    CEP_MAX_LENGTH = 9
    ENDERECO_MAX_LENGTH = 250
    CIDADE_MAX_LENGTH = 80
    ESTADO_MAX_LENGTH = 80
    UF_MAX_LENGTH = 2
    EMAIL_MAX_LENGTH = 250
    SITE_MAX_LENGTH = 250

    data_cadastro = models.DateField(auto_now = True)
    hora_cadastro = models.TimeField(auto_now = True)
    razao_social = models.CharField(max_length=RAZAO_SOCIAL_MAX_LENGTH)
    nome_fantasia = models.CharField(max_length = NOME_FANTASIA_MAX_LENGTH)
    cnpj = models.CharField(max_length=18)
    segmento = models.CharField(max_length=SEGMENTO_MAX_LENGTH)
    contato = models.CharField(max_length=CONTATO_MAX_LENGTH)
    telefone = models.CharField(max_length=TELEFONE_MAX_LENGTH)
    celular = models.CharField(max_length = 20, blank = True, null = True)
    cep = models.CharField(max_length=CEP_MAX_LENGTH)
    endereco = models.CharField(max_length=ENDERECO_MAX_LENGTH)
    cidade = models.CharField(max_length=CIDADE_MAX_LENGTH)
    estado = models.CharField(max_length=ESTADO_MAX_LENGTH)
    uf = models.CharField(max_length=UF_MAX_LENGTH)
    email = models.EmailField(max_length=EMAIL_MAX_LENGTH)
    site = models.URLField(max_length=SITE_MAX_LENGTH, blank=True, null=True)

    def __str__(self):
        return self.razao_social

clientesF/forms.py
# No arquivo forms.py

from django import forms
from .models import Cliente
from .models import Veiculo
from .models import Servico
from .models import Fornecedor

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'sobrenome', 'cpf', 'data_nascimento', 'profissao', 'telefone', 'celular', 'cep', 'endereco', 'cidade', 'estado', 'uf', 'email']

class VeiculoForm(forms.ModelForm):
    class Meta:
        model = Veiculo
        fields = ['placa', 'ano', 'marca', 'modelo', 'cliente']

    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all())
    
class ServicoForm(forms.ModelForm):
    descricao = forms.CharField(max_length=200)
    valor = forms.DecimalField(max_digits=7, decimal_places=2)
    data_entrega = forms.DateField(widget=forms.SelectDateWidget())
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all())
    veiculo = forms.ModelChoiceField(queryset=Veiculo.objects.all())
    detalhes = forms.CharField(max_length=500, required=False)

    class Meta:
        model = Servico
        fields = ['cliente', 'veiculo', 'detalhes', 'descricao', 'valor', 'data_entrega']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['veiculo'].queryset = Veiculo.objects.all()

        if 'cliente' in self.data:
            try:
                cliente_id = int(self.data.get('cliente'))
                self.fields['veiculo'].queryset = Veiculo.objects.filter(cliente_id=cliente_id).order_by('modelo')
            except (ValueError, TypeError):
                pass
        # elif self.instance.pk:
            # self.fields['veiculo'].queryset = self.instance.cliente.veiculo_set.order_by('modelo')

    def clean(self):
        cleaned_data = super().clean()
        veiculo = cleaned_data.get('veiculo')
        cliente = cleaned_data.get('cliente')

        if veiculo and cliente and veiculo.cliente != cliente:
            self.add_error('veiculo', 'O veículo não pertence ao cliente selecionado')

        return cleaned_data


class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = ['razao_social', 'nome_fantasia', 'cnpj', 'contato', 'segmento', 'telefone', 'celular', 'cep', 'endereco', 'cidade', 'estado', 'uf', 'email', 'site']

clientesF/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Cliente, Veiculo
from .forms import ClienteForm
from .forms import VeiculoForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from .models import Servico
from .models import Fornecedor
from .forms import ServicoForm
from .forms import FornecedorForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, '../templates/clientesF/index.html')


#Criar clientes
@login_required
def criar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_clientes')
    else:
        form = ClienteForm()
    return render(request, '../templates/clientesF/criar_cliente.html', {'form': form})  


#Listar clientes
@login_required
def lista_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, '../templates/clientesF/lista_clientes.html', {'clientes': clientes})


#Editar Clientes
@login_required
def editar_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('lista_clientes')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, '../templates/clientesF/editar_cliente.html', {'form': form})


# excluir cliente
@login_required
def excluir_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == 'POST':
        cliente.delete()
        return redirect('lista_clientes')
    return render(request, 'excluir_cliente.html', {'cliente': cliente})


#veiculos
@login_required
def cadastro_veiculo(request):
    if request.method == 'POST':
        form = VeiculoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_veiculos')
    else:
        form = VeiculoForm()

    return render(request, 'clientesF/veiculo_form.html', {'form': form})

@login_required
def lista_veiculos(request):
    veiculos = Veiculo.objects.all()
    return render(request, 'clientesF/veiculo_list.html', {'veiculos': veiculos})

@login_required
def exclui_veiculo(request, pk):
    veiculo = get_object_or_404(Veiculo, pk=pk)
    
    if request.method == 'POST':
        veiculo.delete()
        return redirect('lista_veiculos')
    return render(request, 'clientesF/excluir_veiculo.html', {'veiculo': veiculo})

@login_required
def edita_veiculo(request, pk):
    veiculo = get_object_or_404(Veiculo, pk=pk)
    cliente_pk = veiculo.cliente.pk
    form = VeiculoForm(request.POST or None, instance=veiculo)
    if form.is_valid():
        form.save()
        return redirect('lista_veiculos')
    return render(request, 'clientesF/veiculo_form.html', {'form': form, 'pk': cliente_pk})


## Servico
@login_required
def criar_servico(request):
    form = ServicoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('lista_servicos')
    return render(request, 'clientesF/servico_form.html', {'form': form})
@login_required
def cadastro_servico(request, veiculo_id):
    veiculo = get_object_or_404(Veiculo, pk=veiculo_id)
    cliente = veiculo.cliente

    if request.method == 'POST':
        form = ServicoForm(request.POST)
        if form.is_valid():
            servico = form.save(commit=False)
            servico.veiculo = veiculo
            servico.save()
            return redirect('lista_servicos')
    else:
        form = ServicoForm(initial={'cliente': cliente, 'veiculo': veiculo})

    context = {'form': form}
    return render(request, 'clientesF/servico_form.html', context)

@login_required 
def lista_servicos(request):
    servicos = Servico.objects.all()
    return render(request, 'clientesF/servico_list.html', {'servicos': servicos})

@login_required
def exclui_servico(request, pk):
    servico = get_object_or_404(Servico, pk=pk)
    
    if request.method == 'POST':
        servico.delete()
        return redirect('lista_servicos')
    return render(request, 'clientesF/servico_list.html', {'servico': servico})

@login_required
def edita_servico(request, pk):
    servico = get_object_or_404(Servico, pk=pk)
    if request.method == 'POST':
        form = ServicoForm(request.POST, instance=servico)
        if form.is_valid():
            form.save()
            return redirect('lista_servicos')
    else:
        form = ServicoForm(instance=servico)
    
    return render(request, 'clientesF/edicao_servico.html', {'form': form, 'servico': servico})


## Fornecedor
@login_required   
def cadastrar_fornecedor(request):
    if request.method == 'POST':
        form = FornecedorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('fornecedores_list')
    else:
        form = FornecedorForm()
    return render(request, 'clientesF/fornecedor_form.html', {'form': form})

@login_required 
def fornecedores_list(request):
    fornecedores = Fornecedor.objects.all()
    return render(request, 'clientesF/fornecedores_list.html', {'fornecedores': fornecedores})

@login_required   
def fornecedor_edit(request, pk):
    fornecedor = get_object_or_404(Fornecedor, pk=pk)
    if request.method == "POST":
        form = FornecedorForm(request.POST, instance=fornecedor)
        if form.is_valid():
            fornecedor = form.save(commit=False)
            fornecedor.save()
            return redirect('fornecedores_list')
    else:
        form = FornecedorForm(instance=fornecedor)
    return render(request, 'clientesF/fornecedor_edit.html', {'form': form})

@login_required 
def fornecedor_delete(request, pk):
    fornecedor = get_object_or_404(Fornecedor, pk=pk)
    if request.method == 'POST':
        fornecedor.delete()
        return redirect('fornecedores_list')
    return render(request, 'fornecedor_delete.html', {'fornecedor': fornecedor})

clientesF/templates/base.html
{% load bootstrap4 %}
{% load widget_tweaks %}
{% load static %}
{% load tempo_atual %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    {% bootstrap_css %}
    <meta charset="utf-8">
    <title>{% block title %}{% endblock %}</title>
    <!-- Links para os arquivos CSS do Bootstrap -->
    <link rel="stylesheet" href="{% static '_css/BrennoCar/style.css' %}">
    <link rel="stylesheet" href="{% static '_css/BrennoCar/style_mobile_768.css' %}">
    <link rel="stylesheet" href="{% static '_css/BrennoCar/style_mobile_384.css' %}">
    <link rel="stylesheet" href="{% static '_css/BrennoCar/style_tablet.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/css/bootstrap-datepicker.min.css">
    <script src="//ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datepicker/1.9.0/js/bootstrap-datepicker.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js"></script>
    <script>
      $(document).ready(function() {
        $('#data_nascimento').addClass('datepicker');
        $('.datepicker').datepicker();
      });
    </script>
    <script>
      // inicialize o datepicker para todos os campos com a classe "datepicker"
      $(document).ready(function() {
        $('.datepicker').datepicker({
          format: 'dd-mm-yyyy',
          autoclose: true,
          todayHighlight: true,
        });
      });
    </script>
      {% block css %}{% endblock %}
  </head>
  <body>
    <!-- Barra de navegação do Bootstrap -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url 'index' %}">Brenno Cars - Auto Elétrica</a>
      <div class="logo-injecao-eletronica">
        <img alt="Logotipo injeção eletrônica"
            src="{% static '_images/BrennoCar/Injecao_eletronica-499x499.png' %}">
      </div>
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="cadastroDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Cadastro
              </a>
              <ul class="dropdown-menu" aria-labelledby="cadastroDropdown">
                <li><a class="dropdown-item" href="{% url 'criar_cliente' %}">Clientes</a></li>
                <li><a class="dropdown-item" href="{% url 'cadastro_veiculo' %}">Veículos</a></li>
                <li><a class="dropdown-item" href="{% url 'cadastrar_fornecedor' %}">Fornecedores</a></li>
              </ul>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="consultaDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Consulta
              </a>
              <ul class="dropdown-menu" aria-labelledby="consultaDropdown">
                <li><a class="dropdown-item" href="{% url 'lista_clientes' %}">Clientes</a></li>
                <li><a class="dropdown-item" href="{% url 'lista_veiculos' %}">Veículos</a></li>
                <li><a class="dropdown-item" href="{% url 'lista_servicos' %}">Serviços</a></li>
                <li><a class="dropdown-item" href="{% url 'fornecedores_list' %}">Fornecedores</a></li>
              </ul>
            </li>

            <!--Menu relatórios-->
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="consultaDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Relatórios
              </a>
              <ul class="dropdown-menu" aria-labelledby="consultaDropdown">
                <li><a class="dropdown-item" href="#{% url 'lista_clientes' %}">Clientes</a></li>
                <li><a class="dropdown-item" href="#{% url 'lista_veiculos' %}">Veículos</a></li>
                <li><a class="dropdown-item" href="#{% url 'lista_servicos' %}">Serviços</a></li>
                <li><a class="dropdown-item" href="#{% url 'fornecedores_list' %}">Fornecedores</a></li>
              </ul>
            </li>
            <!--Fim Menu relatórios-->

          </ul>
          <div id="cab-login">
            <span class="bem-vindo">Bem vindo:&nbsp;&nbsp;<small>{{user.first_name}} {{user.last_name}}</small></span>
            <span class="hora">Hora:<small>&nbsp;&nbsp;{% tempo_atual %}</small> </span>
          </div>
        </div>

          <div id="logout">
            <span><a class="logout" href="{% url 'logout' %}">Logout</a></span>
          </divc>
      </div>

    </nav>
    <div class="container-fluid"><br>
      {% block content %}{% endblock %}
    </div>
    <!-- Links para os arquivos JS do Bootstrap -->
    <script src="{% static 'js/BrennoCar/mascara.js' %}"></script>
    <script src="{% static 'js/BrennoCar/cep_scripts.js' %}"></script>
    <script src="{% static 'js/BrennoCar/email_scripts.js' %}"></script>
    <script src="{% static 'js/BrennoCar/jquery.mask.js' %}"></script>
    <script>
      $(document).ready(function() {
        $('#id_data_nascimento').addClass('datepicker');
        $('.datepicker').datepicker();
      });
    </script>
        {% block javascript %}{% endblock %}
  </body>
</html>

clientesF/templates/lista_clientes.html
<!DOCTYPE html>
<html>
  <head>
    <title>Lista de clientes</title>
  </head>
  <body>
    <h1>Lista de clientes</h1>
    <table>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Sobrenome</th>
          <th>E-mail</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for cliente in clientes %}
          <tr>
            <td>{{ cliente.nome }}</td>
            <td>{{ cliente.sobrenome }}</td>
            <td>{{ cliente.email }}</td>
            <td>
              <a href="{% url 'editar_cliente' cliente.pk %}">Editar</a>
              <form action="{% url 'excluir_cliente' cliente.pk %}" method="POST" style="display: inline-block;">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja excluir este cliente?')">Excluir</button>
          </form>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="4">Não há clientes cadastrados.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>