admbreno/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.contrib.auth.views import LoginView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('clientesF.urls')),
    path("admin/", admin.site.urls),
    path('login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('accounts/login/', LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),   
]

clientesF/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import lista_clientes
from .views import criar_cliente
from .views import editar_cliente
from .views import excluir_cliente
from .views import (
    cadastro_veiculo,
    lista_veiculos,
    edita_veiculo,
    exclui_veiculo,
    criar_servico,
    cadastro_servico,
    lista_servicos,
    exclui_servico,
    edita_servico,
    cadastrar_fornecedor,
    fornecedores_list,
    fornecedor_edit,
    fornecedor_delete,
)

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('logout/', auth_views.LogoutView.as_view(template_name='login.html'), name='logout'),
    path('lista_clientes/', views.lista_clientes, name='lista_clientes'),
    path('criar_cliente/', views.criar_cliente, name='criar_cliente'),
    path('editar_cliente/<int:pk>/', editar_cliente, name='editar_cliente'),
    path('excluir_cliente/<int:pk>/', excluir_cliente, name='excluir_cliente'),
    path('lista_veiculos/', lista_veiculos, name='lista_veiculos'),
    path('cadastro_veiculo/', cadastro_veiculo, name='cadastro_veiculo'),
    path('edita_veiculo/<int:pk>/', edita_veiculo, name='edita_veiculo'),
    path('exclui_veiculo/<int:pk>/', exclui_veiculo, name='exclui_veiculo'),
    path('servico/novo/<int:veiculo_id>/', cadastro_servico, name='cadastro_servico'),
    path('lista_servicos/', lista_servicos, name='lista_servicos'),
    path('exclui_servico/<int:pk>/', exclui_servico, name='exclui_servico'),
    path('edita_servico/<int:pk>/', edita_servico, name='edita_servico'),
    path('../accounts/login/', auth_views.LoginView.as_view(), name='login'),
    path('cadastrar_fornecedor/', cadastrar_fornecedor, name='cadastrar_fornecedor'),
    path('fornecedores_list/', fornecedores_list, name='fornecedores_list'),
    path('fornecedor_edit/<int:pk>/', fornecedor_edit, name='fornecedor_edit'),
    path('fornecedor_delete/<int:pk>/', fornecedor_delete, name='fornecedor_delete'),

]

clientesF/models.py
from django.db import models

# Create your models here.
class Cliente(models.Model):
    data_cadastro = models.DateField(auto_now = True)
    hora_cadastro = models.TimeField(auto_now = True)
    nome = models.CharField(max_length=100)
    sobrenome = models.CharField(max_length=100)
    cpf = models.CharField(max_length = 14)
    data_nascimento = models.DateField ()
    profissao = models.CharField(max_length=100)
    telefone = models.CharField(max_length = 15)
    celular = models.CharField(max_length = 15)
    cep = models.CharField(max_length=9)
    endereco = models.CharField(max_length=200)
    cidade = models.CharField(max_length=100)
    estado = models.CharField(max_length = 100)
    uf = models.CharField(max_length = 2)
    email = models.EmailField()

    def __str__(self):
        return self.nome
    

class Veiculo(models.Model):
    data_cadastro = models.DateField(auto_now = True)
    hora_cadastro = models.TimeField(auto_now = True)
    cliente = models.ForeignKey(Cliente, on_delete = models.CASCADE, related_name = 'veiculos')
    marca = models.CharField(max_length=100)
    modelo = models.CharField(max_length=100)
    ano = models.IntegerField()
    placa = models.CharField(max_length=7, unique=True)

    def __str__(self):
        return self.placa
    
class Servico(models.Model):
    data_cadastro = models.DateField(auto_now = True)
    hora_cadastro = models.TimeField(auto_now = True)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    data_entrega = models.DateField()
    cliente = models.ForeignKey(Cliente, on_delete=models.CASCADE, related_name='servicos')
    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE, related_name='servicos')
    descricao = models.CharField(max_length = 200)
    detalhes = models.TextField(blank=True, null=True)
    
    
class Fornecedor(models.Model):
    RAZAO_SOCIAL_MAX_LENGTH = 200
    NOME_FANTASIA_MAX_LENGTH = 200
    SEGMENTO_MAX_LENGTH = 100
    CONTATO_MAX_LENGTH = 200
    TELEFONE_MAX_LENGTH = 20
    CEP_MAX_LENGTH = 9
    ENDERECO_MAX_LENGTH = 250
    CIDADE_MAX_LENGTH = 80
    ESTADO_MAX_LENGTH = 80
    UF_MAX_LENGTH = 2
    EMAIL_MAX_LENGTH = 250
    SITE_MAX_LENGTH = 250

    data_cadastro = models.DateField(auto_now = True)
    hora_cadastro = models.TimeField(auto_now = True)
    razao_social = models.CharField(max_length=RAZAO_SOCIAL_MAX_LENGTH)
    nome_fantasia = models.CharField(max_length = NOME_FANTASIA_MAX_LENGTH)
    cnpj = models.CharField(max_length=18)
    segmento = models.CharField(max_length=SEGMENTO_MAX_LENGTH)
    contato = models.CharField(max_length=CONTATO_MAX_LENGTH)
    telefone = models.CharField(max_length=TELEFONE_MAX_LENGTH)
    celular = models.CharField(max_length = 20, blank = True, null = True)
    cep = models.CharField(max_length=CEP_MAX_LENGTH)
    endereco = models.CharField(max_length=ENDERECO_MAX_LENGTH)
    cidade = models.CharField(max_length=CIDADE_MAX_LENGTH)
    estado = models.CharField(max_length=ESTADO_MAX_LENGTH)
    uf = models.CharField(max_length=UF_MAX_LENGTH)
    email = models.EmailField(max_length=EMAIL_MAX_LENGTH)
    site = models.URLField(max_length=SITE_MAX_LENGTH, blank=True, null=True)

    def __str__(self):
        return self.razao_social

clientesF/forms.py
# No arquivo forms.py

from django import forms
from .models import Cliente
from .models import Veiculo
from .models import Servico
from .models import Fornecedor

class ClienteForm(forms.ModelForm):
    class Meta:
        model = Cliente
        fields = ['nome', 'sobrenome', 'cpf', 'data_nascimento', 'profissao', 'telefone', 'celular', 'cep', 'endereco', 'cidade', 'estado', 'uf', 'email']

class VeiculoForm(forms.ModelForm):
    class Meta:
        model = Veiculo
        fields = ['placa', 'ano', 'marca', 'modelo', 'cliente']

    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all())
    
class ServicoForm(forms.ModelForm):
    descricao = forms.CharField(max_length=200)
    valor = forms.DecimalField(max_digits=7, decimal_places=2)
    data_entrega = forms.DateField(widget=forms.SelectDateWidget())
    cliente = forms.ModelChoiceField(queryset=Cliente.objects.all())
    veiculo = forms.ModelChoiceField(queryset=Veiculo.objects.all())
    detalhes = forms.CharField(max_length=500, required=False)

    class Meta:
        model = Servico
        fields = ['cliente', 'veiculo', 'detalhes', 'descricao', 'valor', 'data_entrega']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['veiculo'].queryset = Veiculo.objects.all()

        if 'cliente' in self.data:
            try:
                cliente_id = int(self.data.get('cliente'))
                self.fields['veiculo'].queryset = Veiculo.objects.filter(cliente_id=cliente_id).order_by('modelo')
            except (ValueError, TypeError):
                pass
        # elif self.instance.pk:
            # self.fields['veiculo'].queryset = self.instance.cliente.veiculo_set.order_by('modelo')

    def clean(self):
        cleaned_data = super().clean()
        veiculo = cleaned_data.get('veiculo')
        cliente = cleaned_data.get('cliente')

        if veiculo and cliente and veiculo.cliente != cliente:
            self.add_error('veiculo', 'O veículo não pertence ao cliente selecionado')

        return cleaned_data


class FornecedorForm(forms.ModelForm):
    class Meta:
        model = Fornecedor
        fields = ['razao_social', 'nome_fantasia', 'cnpj', 'contato', 'segmento', 'telefone', 'celular', 'cep', 'endereco', 'cidade', 'estado', 'uf', 'email', 'site']

clientesF/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .models import Cliente, Veiculo
from .forms import ClienteForm
from .forms import VeiculoForm
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from .models import Servico
from .models import Fornecedor
from .forms import ServicoForm
from .forms import FornecedorForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, '../templates/clientesF/index.html')


#Criar clientes
@login_required
def criar_cliente(request):
    if request.method == 'POST':
        form = ClienteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_clientes')
    else:
        form = ClienteForm()
    return render(request, '../templates/clientesF/criar_cliente.html', {'form': form})  


#Listar clientes
@login_required
def lista_clientes(request):
    clientes = Cliente.objects.all()
    return render(request, '../templates/clientesF/lista_clientes.html', {'clientes': clientes})


#Editar Clientes
@login_required
def editar_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == 'POST':
        form = ClienteForm(request.POST, instance=cliente)
        if form.is_valid():
            form.save()
            return redirect('lista_clientes')
    else:
        form = ClienteForm(instance=cliente)
    return render(request, '../templates/clientesF/editar_cliente.html', {'form': form})


# excluir cliente
@login_required
def excluir_cliente(request, pk):
    cliente = get_object_or_404(Cliente, pk=pk)
    if request.method == 'POST':
        cliente.delete()
        return redirect('lista_clientes')
    return render(request, 'excluir_cliente.html', {'cliente': cliente})


#veiculos
@login_required
def cadastro_veiculo(request):
    if request.method == 'POST':
        form = VeiculoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('lista_veiculos')
    else:
        form = VeiculoForm()

    return render(request, 'clientesF/veiculo_form.html', {'form': form})

@login_required
def lista_veiculos(request):
    veiculos = Veiculo.objects.all()
    return render(request, 'clientesF/veiculo_list.html', {'veiculos': veiculos})

@login_required
def exclui_veiculo(request, pk):
    veiculo = get_object_or_404(Veiculo, pk=pk)
    
    if request.method == 'POST':
        veiculo.delete()
        return redirect('lista_veiculos')
    return render(request, 'clientesF/excluir_veiculo.html', {'veiculo': veiculo})

@login_required
def edita_veiculo(request, pk):
    veiculo = get_object_or_404(Veiculo, pk=pk)
    cliente_pk = veiculo.cliente.pk
    form = VeiculoForm(request.POST or None, instance=veiculo)
    if form.is_valid():
        form.save()
        return redirect('lista_veiculos')
    return render(request, 'clientesF/veiculo_form.html', {'form': form, 'pk': cliente_pk})


## Servico
@login_required
def criar_servico(request):
    form = ServicoForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('lista_servicos')
    return render(request, 'clientesF/servico_form.html', {'form': form})
@login_required
def cadastro_servico(request, veiculo_id):
    veiculo = get_object_or_404(Veiculo, pk=veiculo_id)
    cliente = veiculo.cliente

    if request.method == 'POST':
        form = ServicoForm(request.POST)
        if form.is_valid():
            servico = form.save(commit=False)
            servico.veiculo = veiculo
            servico.save()
            return redirect('lista_servicos')
    else:
        form = ServicoForm(initial={'cliente': cliente, 'veiculo': veiculo})

    context = {'form': form}
    return render(request, 'clientesF/servico_form.html', context)

@login_required 
def lista_servicos(request):
    servicos = Servico.objects.all()
    return render(request, 'clientesF/servico_list.html', {'servicos': servicos})

@login_required
def exclui_servico(request, pk):
    servico = get_object_or_404(Servico, pk=pk)
    
    if request.method == 'POST':
        servico.delete()
        return redirect('lista_servicos')
    return render(request, 'clientesF/servico_list.html', {'servico': servico})

@login_required
def edita_servico(request, pk):
    servico = get_object_or_404(Servico, pk=pk)
    if request.method == 'POST':
        form = ServicoForm(request.POST, instance=servico)
        if form.is_valid():
            form.save()
            return redirect('lista_servicos')
    else:
        form = ServicoForm(instance=servico)
    
    return render(request, 'clientesF/edicao_servico.html', {'form': form, 'servico': servico})


## Fornecedor
@login_required   
def cadastrar_fornecedor(request):
    if request.method == 'POST':
        form = FornecedorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('fornecedores_list')
    else:
        form = FornecedorForm()
    return render(request, 'clientesF/fornecedor_form.html', {'form': form})

@login_required 
def fornecedores_list(request):
    fornecedores = Fornecedor.objects.all()
    return render(request, 'clientesF/fornecedores_list.html', {'fornecedores': fornecedores})

@login_required   
def fornecedor_edit(request, pk):
    fornecedor = get_object_or_404(Fornecedor, pk=pk)
    if request.method == "POST":
        form = FornecedorForm(request.POST, instance=fornecedor)
        if form.is_valid():
            fornecedor = form.save(commit=False)
            fornecedor.save()
            return redirect('fornecedores_list')
    else:
        form = FornecedorForm(instance=fornecedor)
    return render(request, 'clientesF/fornecedor_edit.html', {'form': form})

@login_required 
def fornecedor_delete(request, pk):
    fornecedor = get_object_or_404(Fornecedor, pk=pk)
    if request.method == 'POST':
        fornecedor.delete()
        return redirect('fornecedores_list')
    return render(request, 'fornecedor_delete.html', {'fornecedor': fornecedor})

templates/clientesF/criar_cliente.html
{% extends 'base.html' %}
{% block content %}
  <h2>Cadastrar Cliente</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form }}
    <button class="Save" type="submit">Salvar</button>
  </form>
{% endblock %}

templates/clientesF/edicao_servico.html
{% extends 'base.html' %}
{% block content %}
  <h2>Editar Serviço #{{ servico.id }}</h2>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button class="Save" type="submit">Salvar</button>
  </form>
{% endblock %}

templates/clientesF/editar_cliente.html
{% extends 'base.html' %}
{% block content %}
<h2>Editar Cliente</h2>
<form method="post">
  {% csrf_token %}
  {{ form }}
  <button class="Save" type="submit">Salvar</button>
</form>

{% endblock %}

templates/clientesF/excluir_veiculo.html
{% block content %}
  <h2>Excluir Cliente</h2>
  <form action="{% url 'exclui_veiculo' pk=veiculo.pk %}" method="POST">
    {% csrf_token %}
    <p>Tem certeza que deseja excluir o veiculo "{{ veiculo }}"?</p>
    <input type="submit" value="Excluir">
    <a href="{% url 'lista_veiculos' %}">Cancelar</a>
  </form>
{% endblock %}

templates/clientesF/fornecedor_delete.html
{% extends 'base.html' %}
{% block content %}
  <h2>Delete Fornecedor</h2>
  <p>Are you sure you want to delete "{{ fornecedor.razao_social }}"?</p>

  <form method="post">
    {% csrf_token %}
    <button type="submit">Confirm</button>
    <a href="{% url 'fornecedores_list' %}">Cancel</a>
  </form>
{% endblock %}

templates/clientesF/fornecedor_edit.html
{% extends 'base.html' %}
{% block content %}
  <h2>Editar Fornecedor</h2>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button class="Save" type="submit">Salvar</button>
  </form>
{% endblock %}

templates/clientesF/fornecedor_form.html
{% extends 'base.html' %}
{% block content %}
  <h2>Cadastrar Fornecedor</h2>
  <form method="post">
    {% csrf_token %}
    {{ form }}
    <button class="Save" type="submit">Salvar</button>
  </form>
{% endblock %}

templates/clientesF/fornecedores_list.html
{% extends 'base.html' %}

{% block content %}
<h2>Consulta Fornecedores</h2><br><br>

  <table class="table">
    <thead>
      <tr>
        <th class="consulta_dataCadastro">Cadastro</th>
        <th class="consulta_hora">Hora</th>
        <th class="consulta_razaosocial">Razão Social</th>
        <th class="consulta_cnpj">CNPJ</th>
        <!--<th>Nome Fantasia</th>
        <th>Segmento</th>!-->
        <th class="consulta">Contato</th>
        <!--<th class="consulta_telefone">Telefone</th>!-->
        <th class="consulta_celular">Celular</th>
        <!--<th>CEP</th>!-->
        <th class="consulta_endereco">Endereço</th>
        <!--<th>Cidade</th>!-->
        <!--<th>Estado</th>
        <th>UF</th>!-->
        <th class="consulta">E-mail</th>
        <!--<th>Site</th>!-->
        <th class="consulta_acoes">Ações</th>
      </tr>
    </thead>
    <tbody>
      {% for fornecedor in fornecedores %}
        <tr>
          <td>{{ fornecedor.data_cadastro}}</td>
          <td>{{ fornecedor.hora_cadastro}}</td>
          <td>{{ fornecedor.razao_social }}</td>
          <td>{{ fornecedor.cnpj }}</td>
          <!--<td>{{ fornecedor.nome_fantasia }}</td>
          <td>{{ fornecedor.segmento }}</td>!-->
          <td>{{ fornecedor.contato }}</td>
          <!--<td>{{ fornecedor.telefone }}</td>!-->
          <td>{{ fornecedor.celular }}</td>
          <!--<td>{{ fornecedor.cep }}</td>!-->
          <td>{{ fornecedor.endereco }}</td>
          <!--<td>{{ fornecedor.cidade }}</td>!-->
          <!--<td>{{ fornecedor.estado }}</td>
          <td>{{ fornecedor.uf }}</td>!-->
          <td>{{ fornecedor.email }}</td>
          <!--<td>{{ fornecedor.site }}</td>!-->
          <td>
        <a href="{% url 'fornecedor_edit' fornecedor.pk %}" class="btn btn-warning">Editar</a>
        <form class="consulta" action="{% url 'fornecedor_delete' fornecedor.pk %}" method="POST" >
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja excluir este fornecedor?')">Excluir</button>
          </form>
      </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>
<a href="{% url 'cadastrar_fornecedor' %}" class="btn btn-primary">Cadastrar Fornecedor</a>

 
{% endblock %}

templates/clientesF/index.html
{% extends 'base.html' %}
{% block content %}
<p class="menslogin">É necessário realizar login para utilizar as funcionalidades da pagina</p>
{% endblock %}

templates/clientesF/lista_clientes.html
{% extends 'base.html' %}
{% block content %}
    <h2>Consulta Clientes</h2><br><br>
    <table class="table">
      <thead>
        <tr>
          <th class="consulta_dataCadastro">Cadastro</th>
          <th class="consulta_hora">Hora</th>
          <th class="consulta">Nome</th>
          <th class="consulta_sobrenome">Sobrenome</th>
          <th class="consulta_endereco">Endereço</th>
          <th class="consulta_telefone">Telefone</th>
          <th class="consulta_celular">Celular</th>
          <th class="consulta_email">E-mail</th>
          <th class="consulta_acoes">Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for cliente in clientes %}
          <tr>
            <td>{{ cliente.data_cadastro}}</td>
            <td>{{ cliente.hora_cadastro}}</td>
            <td>{{ cliente.nome }}</td>
            <td>{{ cliente.sobrenome }}</td>
            <td>{{ cliente.endereco }}</td>
            <td>{{ cliente.telefone }}</td>
            <td>{{ cliente.celular }}</td>
            <td>{{ cliente.email }}</td>
            <td>
              <a href="{% url 'editar_cliente' cliente.pk %}" class="btn btn-warning">Editar</a>
          <form class="consulta" action="{% url 'excluir_cliente' cliente.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja excluir este cliente?')">Excluir</button>
          </form>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="4">Não há clientes cadastrados.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    
<a href="{% url 'criar_cliente' %}" class="btn btn-primary">Cadastrar Cliente</a>
{% endblock %}

templates/clientesF/lista_clientes_bkp_2.html
<!DOCTYPE html>
<html>
  <head>
    <title>Lista de clientes</title>
  </head>
  <body>
    <h1>Lista de clientes</h1>
    <table>
      <thead>
        <tr>
          <th>Nome</th>
          <th>Sobrenome</th>
          <th>E-mail</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for cliente in clientes %}
          <tr>
            <td>{{ cliente.nome }}</td>
            <td>{{ cliente.sobrenome }}</td>
            <td>{{ cliente.email }}</td>
            <td>
              <a href="{% url 'editar_cliente' cliente.pk %}">Editar</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="4">Não há clientes cadastrados.</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </body>
</html>

templates/clientesF/servico_form.html
{% extends 'base.html' %}
{% block content %}
  <h2>Cadastrar Serviço</h2>
  <form method="post">
    {% csrf_token %}
    {{ form }}

    <button  class="Save" type="submit" class="btn btn-primary">Salvar</button>
    <a href="{% url 'lista_clientes' %}" class="btn btn-secondary">Cancelar</a>
  </form>
{% endblock %}

{% block extrajs %}
  <script>
    $(document).ready(function() {
      // Bloqueia a edição dos campos cliente e veiculo
      $('select#id_cliente').prop('disabled', true);
      $('select#id_veiculo').prop('disabled', true);
    });
  </script>
{% endblock %}

templates/clientesF/veiculo_form.html
{% extends 'base.html' %}
{% block content %}
  <h2>Cadastrar Veículo</h2>
  <form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="Save" type="submit">Salvar</button>
  </form>
{% endblock %}

templates/clientesF/veiculo_list.html
{% extends 'base.html' %}
{% block content %}
<h2>Consulta Veículos</h2><br><br>

<table class="table">
  <thead>
    <tr>
      <th class="consulta_dataCadastro">Cadastro</th>
      <th class="consulta_hora">Hora</th>
      <th class="consulta">Cliente</th>
      <th class="consulta_montadora">Montadora</th>
      <th class="consulta_modelo">Modelo</th>
      <th class="consulta_ano">Ano</th>
      <th class="consulta_placa">Placa</th>
      <th class="consulta_acoes">Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for veiculo in veiculos %}
    <tr>
      <td>{{ veiculo.data_cadastro}}</td>
      <td>{{ veiculo.hora_cadastro}}</td>
      <td>{{ veiculo.cliente.nome }}</td>
      <td>{{ veiculo.marca }}</td>
      <td>{{ veiculo.modelo }}</td>
      <td>{{ veiculo.ano }}</td>
      <td>{{ veiculo.placa }}</td>
      <td>
        <a href="{% url 'cadastro_servico' veiculo.id %}" class="btn btn-primary">Cadastrar Serviço</a>
        <a href="{% url 'edita_veiculo' veiculo.pk %}" class="btn btn-warning">Editar</a>
        <form class="consulta" action="{% url 'exclui_veiculo' veiculo.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja excluir este veiculo?')">Excluir</button>
          </form>
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>

<a href="{% url 'cadastro_veiculo' %}" class="btn btn-primary">Cadastrar Veículo</a>

{% endblock %}